name: Test

on:
  push:
    branches:
      - dev
  # Add manual trigger for easier testing
  workflow_dispatch: 

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21
        cache: false

    # Run vet and cli-lint for static linting 
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54
    
    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: go test ./...
      